[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "platzky_promocode"
description = "Plugin for revealing promo codes."
authors = [{ name = "ravenw-wing" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = ["platzky==2.0.0a14"]
dynamic = ["version"]


[project.entry-points."platzky.plugins"]
promocode = "platzky_promocode.plugin:PromocodePlugin"

[tool.poetry]
version = "0.4.0"
include = [
    { path = "platzky_promocode/locale/**/*.mo", format = ["wheel", "sdist"] },
]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
black = "^26.3.1"
ruff = ">=0.8.3,<0.16.0"
pyright = "^1.1.390"
coverage = "^7.6.9"
interrogate = "^1.7.0"


[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
show-fixes = true

[tool.ruff.lint]
select = [
    "I",
    "F",
    "E",
    "W",
    "PT",
    "RUF",
]

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false
reportMissingParameterType = true
reportUnknownArgumentType = true
reportUnknownMemberType = true
reportUnknownVariableType = true
reportUnknownParameterType = true
reportUnnecessaryTypeIgnoreComment = true
reportUntypedClassDecorator = false
reportUntypedFunctionDecorator = false
reportUnnecessaryIsInstance = false
reportUnusedFunction = true
reportUntypedBaseClass = false

[tool.pytest.ini_options]
markers = [
    "skip_coverage: skip coverage for this test",
]

[tool.interrogate]
fail-under = 95
ignore-init-method = true
ignore-init-module = true
ignore-magic = true
ignore-private = true
ignore-semiprivate = false
exclude = ["tests", "docs"]
